version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_SERVER_ROOT_URL=http://localhost/
     - GF_INSTALL_PLUGINS=grafana-clock-panel,yesoreyeram-infinity-datasource
    ports:
     - '3000:3000'
    volumes:
     - ./grafana_storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/data.csv:/www/data.csv:ro
