version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_SERVER_ROOT_URL=http://localhost/
     - GF_INSTALL_PLUGINS=grafana-clock-panel,yesoreyeram-infinity-datasource
    ports:
     - '3000:3000'
    volumes:
     - ./grafana_storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/data.csv:/www/data.csv:ro

  # https://prometheus.io/docs/prometheus/latest/getting_started/
  node_exporter_1:
    image: linuxkit/node_exporter:v1.0.0-arm64
    container_name: node_exporter_1
    restart: unless-stopped
    ports:
      - '9100:9100'
    volumes:
      - ./node_exporter/proc/:/host/proc/
      - ./node_exporter/sys/:/host/sys/

  node_exporter_2:
    image: linuxkit/node_exporter:v1.0.0-arm64
    container_name: node_exporter_2
    restart: unless-stopped
    ports:
      - '9101:9100'
    volumes:
      - ./node_exporter/proc/:/host/proc/
      - ./node_exporter/sys/:/host/sys/

  node_exporter_3:
    image: linuxkit/node_exporter:v1.0.0-arm64
    container_name: node_exporter_3
    restart: unless-stopped
    ports:
      - '9102:9100'
    volumes:
      - ./node_exporter/proc/:/host/proc/
      - ./node_exporter/sys/:/host/sys/

